CREATE PROCEDURE usp_DEL_CUST_EMAIL
@email char (25)
AS
DELETE
FROM CUSTOMERS
WHERE EMAIL = @email
GO

CREATE PROCEDURE usp_DEL_EMP_ID
@empid decimal (6,0)
AS 
DELETE
FROM EMPLOYEES
WHERE EMP_ID = @empid
GO

CREATE PROCEDURE usp_DEL_INV_ITEM_ID
@itemid char (5)
AS
DELETE
FROM INVENTORY
WHERE ITEM_ID = @itemid
GO

CREATE PROCEDURE usp_DEL_ORDER_NUM
@ordernum decimal (10,0)
AS
DELETE
FROM INVOICE
WHERE ORDER_NUM = @ordernum
GO