DROP TABLE CUSTOMERS;

DROP TABLE EMPLOYEES;

DROP TABLE INVENTORY;

DROP TABLE INVOICE;

DROP PROCEDURE usp_CHG_CUST_EMAIL;

DROP PROCEDURE usp_CHG_EMP_POSITION;

DROP PROCEDURE usp_CHG_INV_PRICE;

DROP PROCEDURE usp_CHG_INVOICE_DELIVDATE;

DROP PROCEDURE usp_DEL_CUST_EMAIL;

DROP PROCEDURE usp_DEL_EMP_ID;

DROP PROCEDURE usp_DEL_INV_ITEM_ID;

DROP PROCEDURE usp_DEL_ORDER_NUM;

DROP PROCEDURE usp_INS_CUSTOMER;

DROP PROCEDURE usp_INS_EMPLOYEES;

DROP PROCEDURE usp_INS_INVENTORY;

DROP PROCEDURE usp_INS_INVOICE;